23
nss-evening-cohort-12/bangazon-api-jamalbrowning pull request #25
Opened 2021-02-09 16:55 UTC by jamalbrowning

Description of PR that completes issue here...

## Changes

- Completed a Try/Catch for average_rating on the `product.py` model. So that retrieving products is a 201 OK
- Increased `MaxValueValidator to 17000.00 in the `product.py` model.

## Requests / Responses

If this PR contains code that defines a new request/response, or changes an existing one, please put the JSON representations here.

**Request**

GET `/products` retrieves all products

POST `/products` Creates a new product

```json
{ 
    "name": "test",
    "price": 14000.99,
    "description": "It flies high",
    "quantity": 60,
    "location": "Pittsburgh",
    "category_id: 6,
    "image_path": null,
}
```

**Response**

HTTP/1.1 201 OK ( for both requests)

**This is for POST Response**
```json
{
    "id": 102,
    "name": "test",
    "price": 14000.99,
    "number_sold": 0,
    "description": "It flies high",
    "quantity": 60,
    "created_date": "2021-02-09",
    "location": "Pittsburgh",
    "image_path": null,
    "average_rating": 0
}
```

## Testing

Description of how to test code...

- [ ] pull down branch
- [ ] Run `python manage.py makemigrations`
- [ ] Run `python manage.py migrate`
- [ ] Run `python manage.py runserver
- [ ] Open up your API verifier. ( I am using postman)
### GET all products
- [ ] Send a GET request to `http://localhost:8000/products`
### verify max price
- [ ] Send the above POST JSON to `http://localhost:8000/products`

## Related Issues

- Fixes #22 
- Fixes #23

2021-02-09 17:56 UTC, hannahhall requested changes

2021-02-09 17:56 UTC, hannahhall commented on bangazonapi/models/product.py
> +        total_rating = 1
total_rating should still start at 0

2021-02-09 19:41 UTC, jamalbrowning commented
I added another commit for #24 @hannahhall @mitchellblom @BrianBNeal

2021-02-10 00:18 UTC, hannahhall approved these changes
👍  Looks good

For the future though, unless the tickets go together (like test ticket #8 and #23)  you'll want to make separate pr's for each ticket

2021-02-10 00:21 UTC, merged